#开发环境
server:
  port: 8089

#spring配置
spring:
  application:
    name: coronalVaccineSystem
#    数据源的配置
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/covid-19 vaccine system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yx619cj916

  aop:
    auto: true
    proxy-target-class: false

#    mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath*:com/cj/mapper/xml/*.xml  #扫描xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl #日志
    map-underscore-to-camel-case: true #驼峰下划线
  type-aliases-package: com.cj.coronalVaccineSystem #表名对应变小写
  global-config:
    db-config:
      logic-delete-field: deleted #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除，值为1
      logic-not-delete-value: 0

logging:
  # 设置logback.xml位置
#  config: classpath:log/logback.xml
  # 设置log4j.properties位置
  config: classpath:log4j2-spring.xml